services:
  - type: web
    name: petproject
    env: node
    region: singapore
    plan: free
    buildCommand: npm install --include=dev && npm --prefix server install --include=dev && npm run build && npm --prefix server run build
    startCommand: npm --prefix server run start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
