import type { Product, Category, User, Order, Review } from '@/lib/types';

export const categories: Category[] = [
  { id: 'cat-1', name: 'Electronics', slug: 'electronics', image: 'https://picsum.photos/seed/electronics-category/600/400', productCount: 8 },
  { id: 'cat-2', name: 'Fashion', slug: 'fashion', image: 'https://picsum.photos/seed/fashion-category/600/400', productCount: 6 },
  { id: 'cat-3', name: 'Home & Living', slug: 'home-living', image: 'https://picsum.photos/seed/home-living-category/600/400', productCount: 5 },
  { id: 'cat-4', name: 'Beauty', slug: 'beauty', image: 'https://picsum.photos/seed/beauty-category/600/400', productCount: 4 },
  { id: 'cat-5', name: 'Sports', slug: 'sports', image: 'https://picsum.photos/seed/sports-category/600/400', productCount: 4 },
  { id: 'cat-6', name: 'Books', slug: 'books', image: 'https://picsum.photos/seed/books-category/600/400', productCount: 3 },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Wireless Noise-Cancelling Headphones',
    slug: 'wireless-noise-cancelling-headphones',
    description: 'Experience immersive sound with our flagship wireless headphones. Advanced active noise cancellation, 40-hour battery life, and a foldable design that goes wherever you do.',
    price: 349,
    salePrice: 279,
    images: [
      'https://picsum.photos/seed/headphones-prod1/800/800',
      'https://picsum.photos/seed/headphones-prod1b/800/800',
      'https://picsum.photos/seed/headphones-prod1c/800/800',
    ],
    category: 'Electronics',
    tags: ['audio', 'wireless', 'noise-cancelling'],
    stock: 24,
    rating: 4.8,
    reviewCount: 312,
    variants: [
      { type: 'color', value: 'Midnight Black', available: true },
      { type: 'color', value: 'Cloud White', available: true },
      { type: 'color', value: 'Forest Green', available: false },
    ],
  },
  {
    id: 'prod-2',
    name: 'Mechanical Keyboard Pro',
    slug: 'mechanical-keyboard-pro',
    description: 'Tactile switches, RGB backlighting, and aircraft-grade aluminum frame. Built for long coding sessions and competitive gaming alike.',
    price: 159,
    images: [
      'https://picsum.photos/seed/keyboard-prod2/800/800',
      'https://picsum.photos/seed/keyboard-prod2b/800/800',
    ],
    category: 'Electronics',
    tags: ['keyboard', 'mechanical', 'gaming'],
    stock: 42,
    rating: 4.7,
    reviewCount: 198,
    variants: [
      { type: 'size', value: 'TKL', available: true },
      { type: 'size', value: 'Full-size', available: true },
    ],
  },
  {
    id: 'prod-3',
    name: '4K Ultra HD Smart Monitor',
    slug: '4k-ultra-hd-smart-monitor',
    description: '27-inch IPS panel with 4K resolution, USB-C connectivity, and built-in streaming apps. Color-accurate enough for creative work, fast enough for gaming.',
    price: 499,
    salePrice: 399,
    images: [
      'https://picsum.photos/seed/monitor-prod3/800/800',
      'https://picsum.photos/seed/monitor-prod3b/800/800',
    ],
    category: 'Electronics',
    tags: ['monitor', '4k', 'smart'],
    stock: 15,
    rating: 4.6,
    reviewCount: 87,
    variants: [],
  },
  {
    id: 'prod-4',
    name: 'Portable Bluetooth Speaker',
    slug: 'portable-bluetooth-speaker',
    description: '360-degree sound, IPX7 waterproof rating, and 18 hours of playtime. Take your music to the beach, the park, or anywhere in between.',
    price: 129,
    images: [
      'https://picsum.photos/seed/speaker-prod4/800/800',
      'https://picsum.photos/seed/speaker-prod4b/800/800',
    ],
    category: 'Electronics',
    tags: ['audio', 'bluetooth', 'portable'],
    stock: 63,
    rating: 4.5,
    reviewCount: 241,
    variants: [
      { type: 'color', value: 'Ocean Blue', available: true },
      { type: 'color', value: 'Ember Red', available: true },
      { type: 'color', value: 'Charcoal', available: true },
    ],
  },
  {
    id: 'prod-5',
    name: 'Minimalist Leather Backpack',
    slug: 'minimalist-leather-backpack',
    description: 'Full-grain leather meets modern organization. Dedicated laptop sleeve, hidden pockets, and a silhouette that works from morning commute to evening out.',
    price: 249,
    images: [
      'https://picsum.photos/seed/backpack-prod5/800/800',
      'https://picsum.photos/seed/backpack-prod5b/800/800',
    ],
    category: 'Fashion',
    tags: ['bags', 'leather', 'backpack'],
    stock: 18,
    rating: 4.9,
    reviewCount: 156,
    variants: [
      { type: 'size', value: '20L', available: true },
      { type: 'size', value: '30L', available: true },
    ],
  },
  {
    id: 'prod-6',
    name: 'Cashmere Blend Crewneck Sweater',
    slug: 'cashmere-blend-crewneck-sweater',
    description: '70% cashmere, 30% merino wool. The kind of sweater that gets better with every wear. Relaxed fit, ribbed cuffs, and a palette drawn from natural dyes.',
    price: 189,
    salePrice: 149,
    images: [
      'https://picsum.photos/seed/sweater-prod6/800/800',
      'https://picsum.photos/seed/sweater-prod6b/800/800',
    ],
    category: 'Fashion',
    tags: ['clothing', 'cashmere', 'knitwear'],
    stock: 30,
    rating: 4.7,
    reviewCount: 92,
    variants: [
      { type: 'size', value: 'S', available: true },
      { type: 'size', value: 'M', available: true },
      { type: 'size', value: 'L', available: true },
      { type: 'size', value: 'XL', available: false },
    ],
  },
  {
    id: 'prod-7',
    name: 'Titanium Frame Sunglasses',
    slug: 'titanium-frame-sunglasses',
    description: 'Ultra-lightweight titanium frames with polarized CR-39 lenses. 100% UV protection in a shape that flatters every face.',
    price: 275,
    images: [
      'https://picsum.photos/seed/sunglasses-prod7/800/800',
      'https://picsum.photos/seed/sunglasses-prod7b/800/800',
    ],
    category: 'Fashion',
    tags: ['eyewear', 'sunglasses', 'titanium'],
    stock: 22,
    rating: 4.8,
    reviewCount: 74,
    variants: [
      { type: 'color', value: 'Matte Black', available: true },
      { type: 'color', value: 'Brushed Silver', available: true },
      { type: 'color', value: 'Rose Gold', available: false },
    ],
  },
  {
    id: 'prod-8',
    name: 'Handcrafted Ceramic Mug Set',
    slug: 'handcrafted-ceramic-mug-set',
    description: 'A set of four mugs, each with its own subtle glaze variation. Dishwasher and microwave safe. Holds 12oz of your favorite morning ritual.',
    price: 68,
    images: [
      'https://picsum.photos/seed/mug-set-prod8/800/800',
      'https://picsum.photos/seed/mug-set-prod8b/800/800',
    ],
    category: 'Home & Living',
    tags: ['ceramics', 'kitchen', 'handmade'],
    stock: 55,
    rating: 4.9,
    reviewCount: 203,
    variants: [],
  },
  {
    id: 'prod-9',
    name: 'Linen Duvet Cover',
    slug: 'linen-duvet-cover',
    description: 'Stonewashed Belgian linen that gets softer with every wash. Button closure, corner ties, and OEKO-TEX certified. Queen and King sizes available.',
    price: 189,
    salePrice: 149,
    images: [
      'https://picsum.photos/seed/linen-prod9/800/800',
      'https://picsum.photos/seed/linen-prod9b/800/800',
    ],
    category: 'Home & Living',
    tags: ['bedding', 'linen', 'bedroom'],
    stock: 28,
    rating: 4.6,
    reviewCount: 117,
    variants: [
      { type: 'size', value: 'Queen', available: true },
      { type: 'size', value: 'King', available: true },
    ],
  },
  {
    id: 'prod-10',
    name: 'Brass & Walnut Desk Lamp',
    slug: 'brass-walnut-desk-lamp',
    description: 'Weighted brass base, hand-turned walnut arm, and an Edison-style LED bulb included. Dimmable touch control. A lamp that earns its place on any desk.',
    price: 175,
    images: [
      'https://picsum.photos/seed/lamp-prod10/800/800',
      'https://picsum.photos/seed/lamp-prod10b/800/800',
    ],
    category: 'Home & Living',
    tags: ['lighting', 'desk', 'decor'],
    stock: 12,
    rating: 4.8,
    reviewCount: 61,
    variants: [],
  },
  {
    id: 'prod-11',
    name: 'Organic Face Serum',
    slug: 'organic-face-serum',
    description: 'Hyaluronic acid, vitamin C, and bakuchiol in a base of rosehip and jojoba. Absorbs in seconds, delivers visible results in weeks.',
    price: 89,
    images: [
      'https://picsum.photos/seed/serum-prod11/800/800',
      'https://picsum.photos/seed/serum-prod11b/800/800',
    ],
    category: 'Beauty',
    tags: ['skincare', 'serum', 'organic'],
    stock: 80,
    rating: 4.7,
    reviewCount: 428,
    variants: [],
  },
  {
    id: 'prod-12',
    name: 'Solid Perfume — Cedar & Vetiver',
    slug: 'solid-perfume-cedar-vetiver',
    description: 'A warm, grounding fragrance in a portable balm. Notes of cedarwood, vetiver, and a hint of bergamot. Reapply without fuss.',
    price: 45,
    images: [
      'https://picsum.photos/seed/perfume-prod12/800/800',
    ],
    category: 'Beauty',
    tags: ['fragrance', 'perfume', 'portable'],
    stock: 45,
    rating: 4.5,
    reviewCount: 88,
    variants: [],
  },
  {
    id: 'prod-13',
    name: 'Smart Resistance Bands Set',
    slug: 'smart-resistance-bands-set',
    description: 'Five levels of resistance from 10lb to 50lb. Built-in sensors track reps and force via Bluetooth. Companion app with guided workouts included.',
    price: 129,
    salePrice: 99,
    images: [
      'https://picsum.photos/seed/bands-prod13/800/800',
      'https://picsum.photos/seed/bands-prod13b/800/800',
    ],
    category: 'Sports',
    tags: ['fitness', 'resistance', 'smart'],
    stock: 35,
    rating: 4.4,
    reviewCount: 162,
    variants: [],
  },
  {
    id: 'prod-14',
    name: 'Graphite Tennis Racket',
    slug: 'graphite-tennis-racket',
    description: '300g weight, 645cm head size, and a 16x19 string pattern. The racket that sits between control and power, built for the all-court player.',
    price: 249,
    images: [
      'https://picsum.photos/seed/racket-prod14/800/800',
    ],
    category: 'Sports',
    tags: ['tennis', 'racket', 'graphite'],
    stock: 20,
    rating: 4.6,
    reviewCount: 44,
    variants: [],
  },
  {
    id: 'prod-15',
    name: 'Merino Wool Running Socks (3-Pack)',
    slug: 'merino-wool-running-socks',
    description: 'Merino wool blend with targeted cushioning and an anatomical fit. Temperature-regulating, odor-resistant, and built to last 500+ miles.',
    price: 55,
    images: [
      'https://picsum.photos/seed/socks-prod15/800/800',
    ],
    category: 'Sports',
    tags: ['running', 'socks', 'merino'],
    stock: 90,
    rating: 4.8,
    reviewCount: 310,
    variants: [
      { type: 'size', value: 'US 7-9', available: true },
      { type: 'size', value: 'US 10-12', available: true },
      { type: 'size', value: 'US 13+', available: true },
    ],
  },
  {
    id: 'prod-16',
    name: 'Ceramic Matte Planter Trio',
    slug: 'ceramic-matte-planter-trio',
    description: 'Three sizes in a matching matte glaze. Drainage holes and matching saucers included. For the plant parent who appreciates restraint.',
    price: 95,
    images: [
      'https://picsum.photos/seed/planter-prod16/800/800',
      'https://picsum.photos/seed/planter-prod16b/800/800',
    ],
    category: 'Home & Living',
    tags: ['planter', 'ceramic', 'plants'],
    stock: 40,
    rating: 4.7,
    reviewCount: 78,
    variants: [
      { type: 'color', value: 'Sage Green', available: true },
      { type: 'color', value: 'Terracotta', available: true },
      { type: 'color', value: 'Clay White', available: true },
    ],
  },
  {
    id: 'prod-17',
    name: 'Minimalist Running Watch',
    slug: 'minimalist-running-watch',
    description: 'GPS + GLONASS tracking, 7-day battery life, and swim-proof to 50 meters. GPS routes sync to Strava. The watch that disappears on your wrist.',
    price: 299,
    salePrice: 249,
    images: [
      'https://picsum.photos/seed/watch-prod17/800/800',
      'https://picsum.photos/seed/watch-prod17b/800/800',
    ],
    category: 'Sports',
    tags: ['watch', 'gps', 'running'],
    stock: 25,
    rating: 4.7,
    reviewCount: 193,
    variants: [
      { type: 'size', value: '40mm', available: true },
      { type: 'size', value: '44mm', available: true },
    ],
  },
  {
    id: 'prod-18',
    name: 'Designer Tote Bag',
    slug: 'designer-tote-bag',
    description: 'Full-grain vegetable-tanned leather that develops a patina over time. Interior zip pocket, magnetic closure, and hand-stitched handles.',
    price: 325,
    images: [
      'https://picsum.photos/seed/tote-prod18/800/800',
      'https://picsum.photos/seed/tote-prod18b/800/800',
    ],
    category: 'Fashion',
    tags: ['bag', 'leather', 'tote'],
    stock: 14,
    rating: 4.9,
    reviewCount: 58,
    variants: [
      { type: 'color', value: 'Tan', available: true },
      { type: 'color', value: 'Black', available: true },
    ],
  },
  {
    id: 'prod-19',
    name: 'Wireless Charging Pad',
    slug: 'wireless-charging-pad',
    description: '15W fast wireless charging with a fabric-woven surface and LED indicator. Compatible with all Qi-enabled devices. USB-C cable included.',
    price: 49,
    images: [
      'https://picsum.photos/seed/charger-prod19/800/800',
    ],
    category: 'Electronics',
    tags: ['charging', 'wireless', 'accessories'],
    stock: 120,
    rating: 4.3,
    reviewCount: 567,
    variants: [
      { type: 'color', value: 'Charcoal', available: true },
      { type: 'color', value: 'Sand', available: true },
    ],
  },
  {
    id: 'prod-20',
    name: 'Facial Roller & Gua Sha Set',
    slug: 'facial-roller-gua-sha-set',
    description: 'Rose quartz roller and jade gua sha in a velvet-lined box. Cool to the touch, gentle on skin. A ritual that takes 5 minutes and changes everything.',
    price: 72,
    salePrice: 55,
    images: [
      'https://picsum.photos/seed/roller-prod20/800/800',
    ],
    category: 'Beauty',
    tags: ['skincare', 'roller', 'gua-sha'],
    stock: 55,
    rating: 4.6,
    reviewCount: 289,
    variants: [],
  },
  {
    id: 'prod-21',
    name: 'Stainless Steel Water Bottle',
    slug: 'stainless-steel-water-bottle',
    description: 'Double-wall vacuum insulation keeps drinks cold for 24 hours or hot for 12. Powder-coated finish, leak-proof lid, and a 750ml capacity.',
    price: 38,
    images: [
      'https://picsum.photos/seed/bottle-prod21/800/800',
      'https://picsum.photos/seed/bottle-prod21b/800/800',
    ],
    category: 'Sports',
    tags: ['water-bottle', 'insulated', 'eco'],
    stock: 200,
    rating: 4.7,
    reviewCount: 842,
    variants: [
      { type: 'color', value: 'Pacific Blue', available: true },
      { type: 'color', value: 'Forest', available: true },
      { type: 'color', value: 'Black', available: true },
      { type: 'color', value: 'Stainless', available: false },
    ],
  },
  {
    id: 'prod-22',
    name: 'Leather Card Wallet',
    slug: 'leather-card-wallet',
    description: 'Slim profile with a clip that holds up to 8 cards and a cash strap. Full-grain leather that ages beautifully. Fits front pocket.',
    price: 65,
    images: [
      'https://picsum.photos/seed/wallet-prod22/800/800',
    ],
    category: 'Fashion',
    tags: ['wallet', 'leather', 'accessories'],
    stock: 75,
    rating: 4.6,
    reviewCount: 134,
    variants: [
      { type: 'color', value: 'Cognac', available: true },
      { type: 'color', value: 'Black', available: true },
      { type: 'color', value: 'Navy', available: true },
    ],
  },
  {
    id: 'prod-23',
    name: 'Aromatherapy Diffuser',
    slug: 'aromatherapy-diffuser',
    description: 'Ultrasonic diffusion with ambient LED lighting and a 300ml water tank. Timer settings from 1 to 6 hours. Whisper-quiet at 25dB.',
    price: 58,
    images: [
      'https://picsum.photos/seed/diffuser-prod23/800/800',
      'https://picsum.photos/seed/diffuser-prod23b/800/800',
    ],
    category: 'Beauty',
    tags: ['diffuser', 'aromatherapy', 'home'],
    stock: 48,
    rating: 4.5,
    reviewCount: 176,
    variants: [
      { type: 'color', value: 'White', available: true },
      { type: 'color', value: 'Bamboo', available: true },
    ],
  },
  {
    id: 'prod-24',
    name: 'Graphic Design Masterclass',
    slug: 'graphic-design-masterclass',
    description: 'A 40-hour course covering typography, color theory, layout, and portfolio building. Taught by a former Pentagram partner. Includes 12 project files.',
    price: 149,
    salePrice: 99,
    images: [
      'https://picsum.photos/seed/design-course-prod24/800/800',
    ],
    category: 'Books',
    tags: ['design', 'course', 'learning'],
    stock: 999,
    rating: 4.8,
    reviewCount: 1203,
    variants: [],
  },
];

export const users: User[] = [
  { id: 'user-1', name: 'Admin User', email: 'admin@store.com', avatar: 'https://picsum.photos/seed/admin-avatar/200/200', role: 'admin', createdAt: '2024-01-01T00:00:00Z' },
  { id: 'user-2', name: 'Alexandra Reed', email: 'customer@store.com', avatar: 'https://picsum.photos/seed/alex-avatar/200/200', role: 'customer', createdAt: '2024-02-15T00:00:00Z' },
  { id: 'user-3', name: 'Marcus Chen', email: 'marcus.chen@example.com', avatar: 'https://picsum.photos/seed/marcus-avatar/200/200', role: 'customer', createdAt: '2024-03-10T00:00:00Z' },
  { id: 'user-4', name: 'Sophia Nakamura', email: 'sophia.n@example.com', avatar: 'https://picsum.photos/seed/sophia-avatar/200/200', role: 'customer', createdAt: '2024-04-01T00:00:00Z' },
  { id: 'user-5', name: 'James Okafor', email: 'james.okafor@example.com', avatar: 'https://picsum.photos/seed/james-avatar/200/200', role: 'customer', createdAt: '2024-04-20T00:00:00Z' },
  { id: 'user-6', name: 'Elena Vasquez', email: 'elena.v@example.com', avatar: 'https://picsum.photos/seed/elena-avatar/200/200', role: 'customer', createdAt: '2024-05-05T00:00:00Z' },
  { id: 'user-7', name: 'Tom Buchanan', email: 'tom.b@example.com', avatar: 'https://picsum.photos/seed/tom-avatar/200/200', role: 'customer', createdAt: '2024-06-12T00:00:00Z' },
  { id: 'user-8', name: 'Priya Sharma', email: 'priya.sharma@example.com', avatar: 'https://picsum.photos/seed/priya-avatar/200/200', role: 'customer', createdAt: '2024-06-28T00:00:00Z' },
];

export const orders: Order[] = [
  {
    id: 'ORD-7841',
    userId: 'user-2',
    items: [{ productId: 'prod-1', quantity: 1 }, { productId: 'prod-19', quantity: 2 }],
    total: 377,
    status: 'delivered',
    shippingAddress: { fullName: 'Alexandra Reed', line1: '142 Westbrook Lane', city: 'Portland', state: 'OR', zip: '97201', country: 'US' },
    createdAt: '2024-11-10T14:23:00Z',
  },
  {
    id: 'ORD-7842',
    userId: 'user-3',
    items: [{ productId: 'prod-6', quantity: 1 }, { productId: 'prod-22', quantity: 1 }],
    total: 214,
    status: 'delivered',
    shippingAddress: { fullName: 'Marcus Chen', line1: '88 Market Street', line2: 'Apt 4B', city: 'San Francisco', state: 'CA', zip: '94102', country: 'US' },
    createdAt: '2024-11-12T09:45:00Z',
  },
  {
    id: 'ORD-7843',
    userId: 'user-4',
    items: [{ productId: 'prod-11', quantity: 2 }, { productId: 'prod-20', quantity: 1 }],
    total: 233,
    status: 'delivered',
    shippingAddress: { fullName: 'Sophia Nakamura', line1: '23 Magnolia Drive', city: 'Seattle', state: 'WA', zip: '98101', country: 'US' },
    createdAt: '2024-11-15T16:30:00Z',
  },
  {
    id: 'ORD-7844',
    userId: 'user-5',
    items: [{ productId: 'prod-17', quantity: 1 }],
    total: 249,
    status: 'shipped',
    shippingAddress: { fullName: 'James Okafor', line1: '501 River Road', city: 'Austin', state: 'TX', zip: '78701', country: 'US' },
    createdAt: '2024-11-18T11:15:00Z',
  },
  {
    id: 'ORD-7845',
    userId: 'user-6',
    items: [{ productId: 'prod-8', quantity: 1 }, { productId: 'prod-10', quantity: 1 }, { productId: 'prod-16', quantity: 1 }],
    total: 338,
    status: 'processing',
    shippingAddress: { fullName: 'Elena Vasquez', line1: '17 Ocean View Blvd', city: 'Miami', state: 'FL', zip: '33101', country: 'US' },
    createdAt: '2024-11-20T13:00:00Z',
  },
  {
    id: 'ORD-7846',
    userId: 'user-2',
    items: [{ productId: 'prod-3', quantity: 1 }],
    total: 399,
    status: 'processing',
    shippingAddress: { fullName: 'Alexandra Reed', line1: '142 Westbrook Lane', city: 'Portland', state: 'OR', zip: '97201', country: 'US' },
    createdAt: '2024-11-21T10:30:00Z',
  },
  {
    id: 'ORD-7847',
    userId: 'user-7',
    items: [{ productId: 'prod-5', quantity: 1 }, { productId: 'prod-7', quantity: 1 }],
    total: 524,
    status: 'pending',
    shippingAddress: { fullName: 'Tom Buchanan', line1: '9 Elm Street', city: 'Chicago', state: 'IL', zip: '60601', country: 'US' },
    createdAt: '2024-11-22T08:45:00Z',
  },
  {
    id: 'ORD-7848',
    userId: 'user-8',
    items: [{ productId: 'prod-24', quantity: 1 }, { productId: 'prod-2', quantity: 1 }],
    total: 258,
    status: 'pending',
    shippingAddress: { fullName: 'Priya Sharma', line1: '34 Technology Park', city: 'Boston', state: 'MA', zip: '02101', country: 'US' },
    createdAt: '2024-11-22T15:20:00Z',
  },
];

export const reviews: Review[] = [
  { id: 'rev-1', productId: 'prod-1', userId: 'user-3', userName: 'Marcus Chen', rating: 5, comment: 'Best noise cancellation I have ever used. The battery life is incredible.', createdAt: '2024-10-01T10:00:00Z' },
  { id: 'rev-2', productId: 'prod-1', userId: 'user-4', userName: 'Sophia Nakamura', rating: 5, comment: 'Worth every penny. Comfortable for all-day wear.', createdAt: '2024-10-05T14:30:00Z' },
  { id: 'rev-3', productId: 'prod-1', userId: 'user-5', userName: 'James Okafor', rating: 4, comment: 'Great sound. Wish the carrying case was included.', createdAt: '2024-10-10T09:15:00Z' },
  { id: 'rev-4', productId: 'prod-11', userId: 'user-6', userName: 'Elena Vasquez', rating: 5, comment: 'My skin has never looked better. Visible results within 2 weeks.', createdAt: '2024-10-08T11:00:00Z' },
  { id: 'rev-5', productId: 'prod-11', userId: 'user-2', userName: 'Alexandra Reed', rating: 5, comment: 'Absorbs instantly and does not leave a greasy residue.', createdAt: '2024-10-12T16:45:00Z' },
  { id: 'rev-6', productId: 'prod-5', userId: 'user-7', userName: 'Tom Buchanan', rating: 5, comment: 'The leather quality is exceptional. Gets better with age.', createdAt: '2024-10-15T12:00:00Z' },
  { id: 'rev-7', productId: 'prod-8', userId: 'user-8', userName: 'Priya Sharma', rating: 5, comment: 'Beautiful variations in each mug. A joy to use every morning.', createdAt: '2024-10-18T08:30:00Z' },
  { id: 'rev-8', productId: 'prod-17', userId: 'user-3', userName: 'Marcus Chen', rating: 4, comment: 'GPS accuracy is spot on. Battery life is as advertised.', createdAt: '2024-10-20T15:00:00Z' },
];
